config/routes.rb
UrlShortnerPgres::Application.routes.draw do
 
  root :to => 'links#index'

  resources :links
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :short_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ActionController::Base
 def index
 end

 def create
  @link = Link.new(url: params[:url], short_url: SecureRandom.hex(3))
  if @link.save
    redirect_to link_path(@link)
  else
    raise "Did not save URL"
  end
end

def show
  @link = Link.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortnerPgres</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div class="container">
  <h1>Welcome to URL Shortener!</h1>

  <%= form_tag(links_path, :method => 'post') do %>
    <%= text_field_tag(:url)  %>
    <%= submit_tag('Shorten') %>
  <% end %>

</div>

app/views/links/show.html.erb
<div class="container">
  <h1>Here's your short URL!</h1>
  <p><%= '/short/' + @link.short_url %></p>
  You're original url is:<%= @link.url %><br>
  <%= link_to 'go to the real site', @link.url %>
  
  <br><br>
  <a href="/">Create another short URL</a>
</div>